FROM alpine:3.15.4

ENV HELM_VERSION="3.5.4"
ENV KUBECTL_VERSION="1.21.0"

RUN apk add --no-cache \
    git \
    vim \
    curl \
    tar \
    yq \
    jq \
    zsh \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
    python3 \
    py3-pip

# zsh
RUN sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
RUN echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >>~/.zshrc
RUN echo "source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >>~/.zshrc

# change zsh theme to fwalch
RUN sed -i 's/ZSH_THEME=.*/ZSH_THEME="fwalch"/g' ~/.zshrc

# add zsh-sytem-information plugin
RUN git clone https://github.com/hemancini/zsh-sytem-information.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-sytem-information
RUN sed -i 's/plugins=(/plugins=(zsh-sytem-information /g' ~/.zshrc

# add zsh-kubectl-select-kubeconfig plugin
RUN git clone https://github.com/hemancini/zsh-kubectl-select-kubeconfig.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-kubectl-select-kubeconfig
RUN sed -i 's/plugins=(/plugins=(zsh-kubectl-select-kubeconfig /g' ~/.zshrc

# add aws plugin
RUN sed -i 's/plugins=(/plugins=(aws /g' ~/.zshrc

# awscli
RUN pip install awscli

# kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# helm
RUN curl -L "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar xvz && \
    mv linux-amd64/helm /usr/bin/helm && \
    chmod +x /usr/bin/helm && \
    rm -rf linux-amd64

WORKDIR /root
ENTRYPOINT /bin/zsh
